shopping = []
print(shopping)
shopping.append ("milk")
shopping.append ("bread")
shopping.append ("apples")
shopping.append ("mango")
print (shopping)
shopping.remove ("milk")
shopping.remove ("bread")
print (shopping)